package com.github.onsdigital.fanoutcascade.exceptions;

import com.github.onsdigital.fanoutcascade.handlertasks.HandlerTask;
import com.github.onsdigital.fanoutcascade.pool.FanoutCascadeLayer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * @author sullid (David Sullivan) on 24/12/2017
 * @project dp-fanout-cascade
 */
public class DefaultExceptionHandler implements ExceptionHandler {

    private static final Logger LOGGER = LoggerFactory.getLogger(DefaultExceptionHandler.class);

    // Simply logs exceptions generated by Handlers
    @Override
    public void handleLayerException(HandlerTask task, FanoutCascadeLayer layer, Exception e) {
        LOGGER.error(String.format("Exception for task %s in layer %s", task, layer), e);
    }
}
